Traceback (most recent call last):
  File "/home/ds6237/EntropicReasoners/experimental.py", line 25, in <module>
    with open(args.config, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
